In [ ]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
data_path = "/content/drive/MyDrive/OPIM_5671_Data_Mining/Forecasting_project/Global_Superstore.xls"

In [ ]:
df = pd.read_excel(data_path)

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Postal Code,Market,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,10024.0,US,East,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,NaN,APAC,Oceania,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,NaN,APAC,Oceania,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,NaN,EU,Central,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,Senegal,NaN,Africa,Africa,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [ ]:
print(df.shape)
print(df.columns)
df['Country'].value_counts()

(51290, 24)
Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country',
       'Postal Code', 'Market', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

United States                       9994
Australia                           2837
France                              2827
Mexico                              2644
Germany                             2065
China                               1880
United Kingdom                      1633
Brazil                              1599
India                               1555
Indonesia                           1390
Turkey                              1378
Italy                               1108
Nigeria                              905
Spain                                859
Dominican Republic                   742
El Salvador                          736
Cuba                                 724
Honduras                             713
Philippines                          681
New Zealand                          628
Nicaragua                            614
Iran                                 607
Guatemala                            521
Egypt                                487
South Africa                         461
Morocco                              451
Netherlands                          435
Argentina                            390
Panama                               388
Iraq                                 388
Canada                               384
Russia                               384
Ukraine                              381
Democratic Republic of the Congo     379
Saudi Arabia                         361
Colombia                             360
Austria                              331
Thailand                             295
Vietnam                              265
Poland                               252
Japan                                250
Pakistan                             249
Sweden                               203
Algeria                              196
Venezuela                            194
Malaysia                             176
Romania                              173
South Korea                          172
Bangladesh                           163
Peru                                 162
Tanzania                             148
Belgium                              147
Chile                                143
Singapore                            141
Myanmar (Burma)                      136
Angola                               122
Senegal                              112
Cameroon                             110
Cote d'Ivoire                        109
Ireland                              106
Haiti                                104
Israel                               103
Ghana                                102
Zambia                               102
Kazakhstan                           101
Kenya                                 98
Mozambique                            94
Sudan                                 92
Belarus                               80
Zimbabwe                              80
Switzerland                           78
Bulgaria                              75
Czech Republic                        71
Portugal                              70
Norway                                70
Hungary                               66
Denmark                               65
Finland                               64
Ecuador                               56
Madagascar                            56
Afghanistan                           55
Somalia                               52
Lithuania                             50
Uzbekistan                            48
Bolivia                               48
Cambodia                              45
Togo                                  44
Mali                                  43
Niger                                 43
Jordan                                42
Kyrgyzstan                            40
Libya                                 39
Moldova                               39
Uganda                                37
Mongolia                              37
Rwanda                                36
Benin                                 35
Georgia                               33
Croatia                               32
Jamaica                               31
Yemen                                 30
Trinidad and Tobago                   30
Azerbaijan                            29
Syria                                 29
Barbados                              26
Martinique                            25
Turkmenistan                          25
Uruguay                               24
Papua New Guinea                      22
Hong Kong                             21
Nepal                                 19
Guinea                                18
Bosnia and Herzegovina                17
Albania                               16
Qatar                                 16
Liberia                               15
Sierra Leone                          15
United Arab Emirates                  14
Taiwan                                14
Gabon                                 14
Estonia                               13
Tunisia                               13
Djibouti                              12
Lebanon                               12
Paraguay                              12
Mauritania                            10
Namibia                                9
Guinea-Bissau                          9
Guadeloupe                             8
Slovakia                               8
Ethiopia                               7
Sri Lanka                              7
Central African Republic               7
Lesotho                                6
Republic of the Congo                  6
Montenegro                             4
Macedonia                              4
Slovenia                               3
Tajikistan                             3
Equatorial Guinea                      3
Armenia                                3
Swaziland                              2
Bahrain                                2
South Sudan                            2
Chad                                   2
Burundi                                2
Eritrea                                2
Name: Country, dtype: int64

In [ ]:
df_us = df[df['Country'] == 'United States']

In [ ]:
# One order can have multiple products
df_us[df_us['Order ID']=='CA-2012-124891']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Postal Code,Market,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,10024.0,US,East,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
331,32299,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,10024.0,US,East,FUR-TA-10002903,Furniture,Tables,"Bevis Round Bullnose 29"" High Table Top",1090.782,7,0.4,-290.8752,348.18,Critical
26575,32300,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,10024.0,US,East,OFF-PA-10004621,Office Supplies,Paper,Xerox 212,19.440,3,0.0,9.3312,7.24,Critical

In [ ]:
# convert order date to date time variable type
df_us['Order Date'] = pd.to_datetime(df_us['Order Date'])

# Extract order month and order year for aggregation
df_us['Order Month'] = df_us['Order Date'].dt.month
df_us['Order Year'] = df_us['Order Date'].dt.year

#print unique years and months
print(df_us['Order Month'].value_counts())
print(df_us['Order Year'].value_counts())

11    1462
12    1421
9     1386
10     817
5      750
8      710
6      709
7      708
3      680
4      663
1      387
2      301
Name: Order Month, dtype: int64
2014    3319
2013    2580
2012    2102
2011    1993
Name: Order Year, dtype: int64

<ipython-input-47-45867455e3ec>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_us['Order Date'] = pd.to_datetime(df_us['Order Date'])
<ipython-input-47-45867455e3ec>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_us['Order Month'] = df_us['Order Date'].dt.month
<ipython-input-47-45867455e3ec>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_us['Order Year'] = df_us['Order Date'].dt.year

In [ ]:
df_us.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country',
       'Postal Code', 'Market', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority', 'Order Month',
       'Order Year'],
      dtype='object')

In [ ]:
#extract necessary columns from data
df_us = df_us[['Row ID', 'Order ID', 'Order Date', 'Order Month', 'Order Year', 'Sales', 'Discount', 'Order Priority']]

In [ ]:
df_us['Order Priority'].value_counts()

Medium      5710
High        3069
Critical     783
Low          432
Name: Order Priority, dtype: int64

In [ ]:
#Multiplying discount and sales to get discounted_sales for each product
df_us['Discounted_sales'] = df_us['Discount'] * df_us['Sales']

<ipython-input-51-dea7444f1eb9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_us['Discounted_sales'] = df_us['Discount'] * df_us['Sales']

In [ ]:
# group by based on order_id and extract all the necessary variables
df_us_agg = df_us.groupby(['Order ID'],as_index=False).agg(
                                            sales = pd.NamedAgg(column='Sales', aggfunc='sum'),
                                            order_date = pd.NamedAgg(column='Order Date', aggfunc=lambda x: x.head(1)),
                                            Discount_avg = pd.NamedAgg(column='Discount', aggfunc='mean'),
                                            Discount_min = pd.NamedAgg(column='Discount', aggfunc='min'),
                                            Discounted_sales_sum = pd.NamedAgg(column='Discounted_sales', aggfunc='sum'),
                                            critical = pd.NamedAgg(column='Order Priority', aggfunc=lambda x: 1 if (x.iloc[0]=='Critical') else 0),
                                            high_priority = pd.NamedAgg(column='Order Priority', aggfunc=lambda x: 1 if (x.iloc[0]=='High') else 0),
                                            low_priority = pd.NamedAgg(column='Order Priority', aggfunc=lambda x: 1 if (x.iloc[0]=='Low') else 0),
                                            medium_priority = pd.NamedAgg(column='Order Priority', aggfunc=lambda x: 1 if (x.iloc[0]=='Medium') else 0),
                                            )
df_us_agg.head(5)

,Order ID,sales,order_date,Discount_avg,Discount_min,Discounted_sales_sum,critical,high_priority,low_priority,medium_priority
0,CA-2011-100006,377.970,2011-09-07,0.0,0.0,0.0000,0,0,0,1
1,CA-2011-100090,699.192,2011-07-08,0.2,0.2,139.8384,0,0,0,1
2,CA-2011-100293,91.056,2011-03-14,0.2,0.2,18.2112,0,0,0,1
3,CA-2011-100328,3.928,2011-01-29,0.2,0.2,0.7856,0,0,0,1
4,CA-2011-100363,21.376,2011-04-08,0.2,0.2,4.2752,0,0,0,1

In [ ]:
df_us_agg.columns

Index(['Order ID', 'sales', 'order_date', 'Discount_avg', 'Discount_min',
       'Discounted_sales_sum', 'critical', 'high_priority', 'low_priority',
       'medium_priority'],
      dtype='object')

In [ ]:
df_us_agg['Total_Discount_per_order'] = df_us_agg['Discounted_sales_sum']/df_us_agg['sales']

In [ ]:
df_us_agg.set_index('order_date', inplace=True)
monthly_agg = df_us_agg.resample('M').agg(sales=pd.NamedAgg(column='sales', aggfunc='sum'),
                                            Discount_avg = pd.NamedAgg(column='Discount_avg', aggfunc='mean'),
                                            Discount_min = pd.NamedAgg(column='Discount_min', aggfunc='min'),
                                            Total_Discount_per_order_avg = pd.NamedAgg(column='Total_Discount_per_order', aggfunc='mean'),
                                            critical_orders = pd.NamedAgg(column='critical', aggfunc='sum'),
                                            high_priority_orders = pd.NamedAgg(column='high_priority', aggfunc='sum'),
                                            low_priority_orders = pd.NamedAgg(column='low_priority', aggfunc='sum'),
                                            medium_priority_orders = pd.NamedAgg(column='medium_priority', aggfunc='sum'),
                                          )
monthly_agg.reset_index(inplace=True)

In [ ]:
monthly_agg.to_csv('/content/drive/MyDrive/OPIM_5671_Data_Mining/Forecasting_project/MONTHLY_SALES_discount.csv')

In [ ]:
monthly_agg

,order_date,sales,Discount_avg,Discount_min,Total_Discount_per_order_avg,critical_orders,high_priority_orders,low_priority_orders,medium_priority_orders
0,2011-01-31,13946.2290,0.158199,0.0,0.144853,6,10,1,14
1,2011-02-28,4810.5580,0.206897,0.0,0.199011,1,12,2,14
2,2011-03-31,55691.0090,0.170312,0.0,0.173543,5,24,1,41
3,2011-04-30,28295.3450,0.109785,0.0,0.113578,7,17,2,40
4,2011-05-31,23648.2870,0.154348,0.0,0.163160,6,15,3,45
5,2011-06-30,34595.1276,0.162864,0.0,0.161257,3,22,2,39
6,2011-07-31,33946.3930,0.149808,0.0,0.142377,4,24,5,32
7,2011-08-31,27909.4685,0.136204,0.0,0.146814,4,23,2,43
8,2011-09-30,81777.3508,0.180159,0.0,0.184723,6,46,4,74
9,2011-10-31,31453.3930,0.156661,0.0,0.142824,13,25,0,40
10,2011-11-30,78628.7167,0.148623,0.0,0.148536,12,42,11,86
11,2011-12-31,69545.6205,0.201228,0.0,0.200615,9,45,4,83
12,2012-01-31,18174.0756,0.172759,0.0,0.176086,2,6,2,19
13,2012-02-29,12210.8670,0.108421,0.0,0.094404,4,11,4,19
14,2012-03-31,38466.7960,0.140260,0.0,0.136942,7,25,1,44
15,2012-04-30,34195.2085,0.167863,0.0,0.167371,3,16,5,48
16,2012-05-31,30131.6865,0.155919,0.0,0.148785,5,22,8,39
17,2012-06-30,24797.2920,0.160977,0.0,0.157147,3,20,2,43
18,2012-07-31,28765.3250,0.187583,0.0,0.177940,7,19,4,36
19,2012-08-31,36898.3322,0.136381,0.0,0.132585,4,27,1,36
20,2012-09-30,64595.9180,0.138264,0.0,0.131940,8,41,5,86
21,2012-10-31,31404.9235,0.165192,0.0,0.165120,7,25,4,51
22,2012-11-30,75972.5635,0.167569,0.0,0.159508,19,42,8,89
23,2012-12-31,74919.5212,0.140614,0.0,0.149803,11,49,3,98
24,2013-01-31,18542.4910,0.118056,0.0,0.116912,5,12,3,28
25,2013-02-28,22867.7110,0.102273,0.0,0.109719,6,11,4,23
26,2013-03-31,51186.2170,0.168902,0.0,0.163961,7,30,4,44
27,2013-04-30,39248.5930,0.150344,0.0,0.150179,4,25,5,54
28,2013-05-31,56691.0770,0.174443,0.0,0.158934,7,29,4,69
29,2013-06-30,39430.4430,0.142234,0.0,0.141982,12,37,1,47
30,2013-07-31,38440.7550,0.176021,0.0,0.174410,11,26,3,56
31,2013-08-31,33265.5643,0.184864,0.0,0.174356,12,22,6,51
32,2013-09-30,72908.1089,0.161932,0.0,0.159690,14,60,5,112
33,2013-10-31,56463.1300,0.171277,0.0,0.170717,9,27,9,57
34,2013-11-30,82192.3228,0.150860,0.0,0.145167,19,52,6,109
35,2013-12-31,97237.4170,0.136403,0.0,0.135216,13,49,6,105
36,2014-01-31,44703.1420,0.157301,0.0,0.150267,3,21,6,44
37,2014-02-28,20283.5134,0.155833,0.0,0.156354,0,17,2,33
38,2014-03-31,53908.9620,0.129919,0.0,0.131974,5,35,6,65
39,2014-04-30,40112.4209,0.184196,0.0,0.177614,11,35,7,59
40,2014-05-31,45651.2362,0.154244,0.0,0.146815,4,49,5,72
41,2014-06-30,48259.7487,0.172289,0.0,0.171455,8,42,5,70
42,2014-07-31,48428.3650,0.147928,0.0,0.150750,10,35,3,64
43,2014-08-31,61516.0860,0.155102,0.0,0.151946,5,34,3,68
44,2014-09-30,90488.7220,0.144546,0.0,0.143845,18,85,6,120
45,2014-10-31,77793.7552,0.171087,0.0,0.167944,13,47,10,80
46,2014-11-30,112326.4710,0.159408,0.0,0.157904,21,69,16,146
47,2014-12-31,90474.6008,0.151243,0.0,0.146339,15,74,16,130

In [ ]:
# # Set the date column as the index (required for resampling)
# df_us.set_index('Order Date', inplace=True)

# # Define a dictionary where keys are column names, and values are the aggregation functions
# agg_functions = {
#     'Sales': 'sum',       # Sum these columns
#     'Discount' : 'mean',
# }
# monthly_agg = df_us.resample('M').agg(agg_functions)

# # Reset the index to get the date column back as a regular column
# monthly_agg.reset_index(inplace=True)

# # Print the resulting DataFrame
# print(monthly_agg)

   Order Date        Sales
0  2011-01-31   13946.2290
1  2011-02-28    4810.5580
2  2011-03-31   55691.0090
3  2011-04-30   28295.3450
4  2011-05-31   23648.2870
5  2011-06-30   34595.1276
6  2011-07-31   33946.3930
7  2011-08-31   27909.4685
8  2011-09-30   81777.3508
9  2011-10-31   31453.3930
10 2011-11-30   78628.7167
11 2011-12-31   69545.6205
12 2012-01-31   18174.0756
13 2012-02-29   12210.8670
14 2012-03-31   38466.7960
15 2012-04-30   34195.2085
16 2012-05-31   30131.6865
17 2012-06-30   24797.2920
18 2012-07-31   28765.3250
19 2012-08-31   36898.3322
20 2012-09-30   64595.9180
21 2012-10-31   31404.9235
22 2012-11-30   75972.5635
23 2012-12-31   74919.5212
24 2013-01-31   18542.4910
25 2013-02-28   22867.7110
26 2013-03-31   51186.2170
27 2013-04-30   39248.5930
28 2013-05-31   56691.0770
29 2013-06-30   39430.4430
30 2013-07-31   38440.7550
31 2013-08-31   33265.5643
32 2013-09-30   72908.1089
33 2013-10-31   56463.1300
34 2013-11-30   82192.3228
35 2013-12-31   97237.4170
36 2014-01-31   44703.1420
37 2014-02-28   20283.5134
38 2014-03-31   53908.9620
39 2014-04-30   40112.4209
40 2014-05-31   45651.2362
41 2014-06-30   48259.7487
42 2014-07-31   48428.3650
43 2014-08-31   61516.0860
44 2014-09-30   90488.7220
45 2014-10-31   77793.7552
46 2014-11-30  112326.4710
47 2014-12-31   90474.6008